# Sesión 5 de Python: Estructuras de Datos Lineales y Bidimensionales

![datos-python.jpg](https://raw.githubusercontent.com/KevinChenWu/TallerPython/main/images/datos-python.jpg)

#Listas

![listas.jpg](https://raw.githubusercontent.com/KevinChenWu/TallerPython/main/images/listas.jpg)

Una lista es una estructura de datos y un tipo de dato en python con características especiales. Lo especial de las listas en Python es que permiten almacenar cualquier tipo de valor como enteros, cadenas y hasta otras funciones

In [1]:
lista = [1, 2.5, 'DevCode', [5,6] ,4]
print(type(lista))
lista1 = [1,2,3,4]
print(lista)


<class 'list'>
[1, 2.5, 'DevCode', [5, 6], 4]


Una lista es un arreglo de elementos donde se puede ingresar cualquier tipo de dato, para acceder a estos datos se hace mediante un índice.

In [3]:
lista = [1, 2.5, 'DevCode', [5,6] ,4,5]
print(lista[0]) # 1
print(lista[1]) # 2.5
print(lista[1:3]) # Desde índice 1 hasta 3 no inclusive [1,3[ (2.5, 'DevCode')


1
2.5
[2.5, 'DevCode']


## Métodos de las Listas


![list.png](https://raw.githubusercontent.com/KevinChenWu/TallerPython/main/images/list.png)

In [4]:
my_list = [2, 5, 'DevCode', 1.2, 5]

# Append()
my_list.append(10) # [2, 5, 'DevCode', 1.2, 5, 10]
my_list.append([2,5]) # [2, 5, 'DevCode', 1.2, 5, 10, [2, 5]]
print(my_list)

# pop()
my_list.pop(3) # se le pasa el indice
print(my_list)


# Extend()
my_list.extend([2,5]) # [2, 5, 'DevCode', 5, 10, [2, 5], 2, 5]
print(my_list)


# Remove()
my_list.remove(2) # [5, 'DevCode', 5, 10, [2, 5], 2, 5]
print(my_list)


# Index()
my_list.index('DevCode') # 2
print(my_list.index('DevCode'))


# Count()
my_list.count(5) # 3
print(my_list.count(5))


# Reverse()
my_list.reverse() # [5, 2, [2, 5], 10, 5 'DevCode', 5]
print(my_list)


[2, 5, 'DevCode', 1.2, 5, 10, [2, 5]]
[2, 5, 'DevCode', 5, 10, [2, 5]]
[2, 5, 'DevCode', 5, 10, [2, 5], 2, 5]
[5, 'DevCode', 5, 10, [2, 5], 2, 5]
1
3
[5, 2, [2, 5], 10, 5, 'DevCode', 5]


#Tuplas

![python-tuple.jpg](https://raw.githubusercontent.com/KevinChenWu/TallerPython/main/images/python-tuple.jpg)

Las tuplas en Python o tuples son muy similares a las listas, pero con dos diferencias. Son inmutables, lo que significa que no pueden ser modificadas una vez declaradas, y en vez de inicializarse con corchetes [ ] se hace con ( ). Dependiendo de lo que se quiera hacer, las tuplas pueden ser más rápidas.

In [5]:
tupla = (1, 2, 3)
print(tupla) # (1, 2, 3)


tupla = 1, 2, 3
print(type(tupla)) # <class 'tuple'>
print(tupla)       # (1, 2, 3)


tupla = (1, 2, 3)
for t in tupla:
    print(t) # 1, 2, 3

# casteo de tuplas a listas
lista = [1, 2, 3]
tupla = tuple(lista)
lista1 = list(tupla)
print(type(lista1)) # <class 'list'>
print(lista1)       # [1, 2, 3]


(1, 2, 3)
<class 'tuple'>
(1, 2, 3)
1
2
3
<class 'list'>
[1, 2, 3]


## Métodos de las Tuplas


![tuple.png](https://raw.githubusercontent.com/KevinChenWu/TallerPython/main/images/tuple.png)

In [6]:
# len(): tamaño
l = (1,2,3,4)
print(len(l)) #4

# max(): valor máximo
l = (1,2,3,100)
print(max(l)) #100

# min(): valor mínimo
l = (1,2,3,100)
print(min(l)) #1

# sum(): suma todos los elementos
l = (1,2,3)
print(sum(l)) #6

# any(): busca si algún elemento es True/1
l = (True,1,0)
print(any(l)) #True

# any()
l = (0,0,0)
print(any(l)) #False

# all(): busca si todos los elementos son True/1
l = (1,True,1)
print(all(l)) #True

# all()
l = (1,True,0)
print(all(l)) #False

# sorted(): ordena los números de menor a mayor y lo retorna en una lista
numbers = (4, 2, 12, 8)
sorted_numbers = sorted(numbers)
print(sorted_numbers)

# count(): cuenta las apariciones de un cierto elemento
l = (1, 1, 1, 3, 5)
print(l.count(1)) #3


# index(): devuelve el índice de un cierto elemento
l = (7, 7, 7, 3, 5)
print(l.index(5)) #4

l = (7, 7, 7, 3, 5)
#print(l.index(35)) # Error! ValueError

l = (7, 7, 7, 3, 5)
print(l.index(7, 2)) # Busca el elemento a partir de un índice


4
100
1
6
True
False
True
False
[2, 4, 8, 12]
3
4
2


#Diccionarios

![diccionarios-en-python.png](https://raw.githubusercontent.com/KevinChenWu/TallerPython/main/images/diccionarios-en-python.png)

Un Diccionario es una estructura de datos y un tipo de dato en Python con características especiales que permite almacenar cualquier tipo de valor como enteros, cadenas, listas e incluso otras funciones. Estos diccionarios permiten además identificar cada elemento por una clave (Key). Para definir un diccionario, se encierra el listado de valores entre llaves. Las parejas de clave y valor se separan con comas, y la clave y el valor se separan con dos puntos. Las llaves solo pueden ser enteros, strings o tuplas (inmutables).

![dictionary.png](https://raw.githubusercontent.com/KevinChenWu/TallerPython/main/images/dictionary.png)

In [7]:
diccionario = {'nombre' : 'Carlos', 'edad' : 22, 'cursos': ['Python','Django']}

print(diccionario['nombre']) # Carlos
print(diccionario['edad'])# 22
print(diccionario['cursos']) # ['Python','Django']

print(diccionario['cursos'][0])# Python
print(diccionario['cursos'][1])# Django

for key in diccionario:
  print(f"{key} : {diccionario[key]}")


Carlos
22
['Python', 'Django']
Python
Django
nombre : Carlos
edad : 22
cursos : ['Python', 'Django']


## Métodos de los Diccionarios

In [8]:
# dict()
dic = dict(nombre='nestor', apellido='Plasencia', edad=22)
print(dic)

# items()
dic = {'a' : 1, 'b' : 2, 'c' : 3 , 'd' : 4}
items = dic.items()
print(items)

# keys()
dic = {'a' : 1, 'b' : 2, 'c' : 3 , 'd' : 4}
keys = dic.keys()
print(keys)

# values()
dic =  {'a' : 1, 'b' : 2, 'c' : 3 , 'd' : 4}
values = dic.values()
print(values)

# clear()
dic1 =  {'a' : 1, 'b' : 2, 'c' : 3 , 'd' : 4}
dic1.clear()
print(dic1)

# copy()
dic = {'a' : 1, 'b' : 2, 'c' : 3 , 'd' : 4}
dic1 = dic.copy()
print(dic1)

# Cuidado con copy() al tener elementos mutables
dic = {'a': 1, 'b': 2, 'c': 3, 'd': [1, 3]}
dic1 = dic.copy()
dic['d'][0] = 50
print(dic1)
print(dic)

# Solución: usar deepcopy() para copiar las listas anidadas

# get()
dic = {'a' : 1, 'b' : 2, 'c' : 3 , 'd' : 4}
valor = dic.get('b') 
print(valor)

# pop()
dic = {'a' : 1, 'b' : 2, 'c' : 3 , 'd' : 4}
valor = dic.pop('b') 
print(valor)
print(dic)


{'nombre': 'nestor', 'apellido': 'Plasencia', 'edad': 22}
dict_items([('a', 1), ('b', 2), ('c', 3), ('d', 4)])
dict_keys(['a', 'b', 'c', 'd'])
dict_values([1, 2, 3, 4])
{}
{'a': 1, 'b': 2, 'c': 3, 'd': 4}
{'a': 1, 'b': 2, 'c': 3, 'd': [50, 3]}
{'a': 1, 'b': 2, 'c': 3, 'd': [50, 3]}
2
2
{'a': 1, 'c': 3, 'd': 4}


#Matrices

![matriz.jpg](https://raw.githubusercontent.com/KevinChenWu/TallerPython/main/images/matriz.jpg)

Una matriz es una
lista de listas que se interpreta desde el punto de vista matemático. Es decir,
la estructura m = [ [1,2], [3,4] ] se interpreta como la matriz 2x2 cuya
primera fila es (1,2) y cuya segunda fila es (3,4)

![reshape.png](https://raw.githubusercontent.com/KevinChenWu/TallerPython/main/images/reshape.png)

In [9]:
m = [[1,2],[3,4]]
print(m)

def matriz2str(matriz):
 cadena = ''
 for i in range(len(matriz)):
   cadena += "["
   for j in range(len(matriz[i])):
     cadena += f" {matriz[i][j]} "
   cadena += "]\n"
 return cadena


s = matriz2str(m)
print(s)


[[1, 2], [3, 4]]
[ 1  2 ]
[ 3  4 ]



In [10]:
import numpy as np
matrix_aux = [[1,2,3],
              [4,5,6]]

m = np.array(matrix_aux)

print(m[1,1])
print(m[:,2])
print(m[0,:])
print(m[0,::-1])

print(m.sum())
print(m[0,:].sum())
print(m.flatten())


5
[3 6]
[1 2 3]
[3 2 1]
21
6
[1 2 3 4 5 6]


Ejemplo listas #1


* Sume todos los numeros de una lista. 
* Multiplique todos los elementos dentro de una lista.
* Encontrar el valor mayor dentro de una lista.
* Encontrar los valores que se repiten en una lista.
* Contar las veces que se repite un numero dado. 


In [11]:
notas = [50,60,100,90,85,70,50,60,60]
total_notas = 0
mult_notas = 1

#Suma
for nota in notas:
  #total_notas = total_notas + nota
  total_notas += nota

print(sum(notas))
print(total_notas)
  
#Multiplicacion
for nota in notas:
  mult_notas *= nota

print(mult_notas)

#Numero mayor 
mayor = notas[0]
for nota in range(len(notas)): # range = 0,1,2,3,4,5
  if notas[nota] > mayor:
    mayor = notas[nota]

print(mayor)
print(max(notas))

#Encontrar las repeticiones en una lista
repeticiones = []
unica_repeticion = []

for nota in notas:
  if notas.count(nota) == 1:
    unica_repeticion.append(nota)
  elif nota not in repeticiones:
    repeticiones.append(nota)

print(repeticiones) 
print(unica_repeticion)

#Cuenta cuantas veces se repite un numero dado 
contador = 0
num = 50
for nota in notas:
  if nota == num:
    contador +=1

print(contador)


625
625
28917000000000000
100
100
[50, 60]
[100, 90, 85, 70]
2
